/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PolitiqueConfidentialiteRouteImport } from './routes/politique-confidentialite'
import { Route as AuthenticatedIntranetRouteRouteImport } from './routes/_authenticated/intranet/route'
import { Route as PartageJetonRouteImport } from './routes/partage.$jeton'
import { Route as AuthenticatedIntranetIndexRouteImport } from './routes/_authenticated/intranet/index'
import { Route as AuthenticatedIntranetAcquisRouteImport } from './routes/_authenticated/intranet/acquis'
import { Route as AuthenticatedIntranetAdminRouteImport } from './routes/_authenticated/intranet/admin'
import { Route as AuthenticatedIntranetBudgetRouteImport } from './routes/_authenticated/intranet/budget'
import { Route as AuthenticatedIntranetCoffreRouteImport } from './routes/_authenticated/intranet/coffre'
import { Route as AuthenticatedIntranetDemandeFormationRouteImport } from './routes/_authenticated/intranet/demande-formation'
import { Route as AuthenticatedIntranetFormationsRouteImport } from './routes/_authenticated/intranet/formations'
import { Route as AuthenticatedIntranetPositionnementRouteImport } from './routes/_authenticated/intranet/positionnement'
import { Route as AuthenticatedIntranetProfilRouteImport } from './routes/_authenticated/intranet/profil'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueConfidentialiteRoute =
  PolitiqueConfidentialiteRouteImport.update({
    id: '/politique-confidentialite',
    path: '/politique-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedIntranetRouteRoute =
  AuthenticatedIntranetRouteRouteImport.update({
    id: '/intranet',
    path: '/intranet',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const PartageJetonRoute = PartageJetonRouteImport.update({
  id: '/partage/$jeton',
  path: '/partage/$jeton',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntranetIndexRoute =
  AuthenticatedIntranetIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetAcquisRoute =
  AuthenticatedIntranetAcquisRouteImport.update({
    id: '/acquis',
    path: '/acquis',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetAdminRoute =
  AuthenticatedIntranetAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetBudgetRoute =
  AuthenticatedIntranetBudgetRouteImport.update({
    id: '/budget',
    path: '/budget',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetCoffreRoute =
  AuthenticatedIntranetCoffreRouteImport.update({
    id: '/coffre',
    path: '/coffre',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetDemandeFormationRoute =
  AuthenticatedIntranetDemandeFormationRouteImport.update({
    id: '/demande-formation',
    path: '/demande-formation',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetFormationsRoute =
  AuthenticatedIntranetFormationsRouteImport.update({
    id: '/formations',
    path: '/formations',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetPositionnementRoute =
  AuthenticatedIntranetPositionnementRouteImport.update({
    id: '/positionnement',
    path: '/positionnement',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const AuthenticatedIntranetProfilRoute =
  AuthenticatedIntranetProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedIntranetRouteRoute,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/intranet': typeof AuthenticatedIntranetRouteRouteWithChildren
  '/partage/$jeton': typeof PartageJetonRoute
  '/intranet/acquis': typeof AuthenticatedIntranetAcquisRoute
  '/intranet/admin': typeof AuthenticatedIntranetAdminRoute
  '/intranet/budget': typeof AuthenticatedIntranetBudgetRoute
  '/intranet/coffre': typeof AuthenticatedIntranetCoffreRoute
  '/intranet/demande-formation': typeof AuthenticatedIntranetDemandeFormationRoute
  '/intranet/formations': typeof AuthenticatedIntranetFormationsRoute
  '/intranet/positionnement': typeof AuthenticatedIntranetPositionnementRoute
  '/intranet/profil': typeof AuthenticatedIntranetProfilRoute
  '/intranet/': typeof AuthenticatedIntranetIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/partage/$jeton': typeof PartageJetonRoute
  '/intranet/acquis': typeof AuthenticatedIntranetAcquisRoute
  '/intranet/admin': typeof AuthenticatedIntranetAdminRoute
  '/intranet/budget': typeof AuthenticatedIntranetBudgetRoute
  '/intranet/coffre': typeof AuthenticatedIntranetCoffreRoute
  '/intranet/demande-formation': typeof AuthenticatedIntranetDemandeFormationRoute
  '/intranet/formations': typeof AuthenticatedIntranetFormationsRoute
  '/intranet/positionnement': typeof AuthenticatedIntranetPositionnementRoute
  '/intranet/profil': typeof AuthenticatedIntranetProfilRoute
  '/intranet': typeof AuthenticatedIntranetIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/politique-confidentialite': typeof PolitiqueConfidentialiteRoute
  '/_authenticated/intranet': typeof AuthenticatedIntranetRouteRouteWithChildren
  '/partage/$jeton': typeof PartageJetonRoute
  '/_authenticated/intranet/acquis': typeof AuthenticatedIntranetAcquisRoute
  '/_authenticated/intranet/admin': typeof AuthenticatedIntranetAdminRoute
  '/_authenticated/intranet/budget': typeof AuthenticatedIntranetBudgetRoute
  '/_authenticated/intranet/coffre': typeof AuthenticatedIntranetCoffreRoute
  '/_authenticated/intranet/demande-formation': typeof AuthenticatedIntranetDemandeFormationRoute
  '/_authenticated/intranet/formations': typeof AuthenticatedIntranetFormationsRoute
  '/_authenticated/intranet/positionnement': typeof AuthenticatedIntranetPositionnementRoute
  '/_authenticated/intranet/profil': typeof AuthenticatedIntranetProfilRoute
  '/_authenticated/intranet/': typeof AuthenticatedIntranetIndexRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/politique-confidentialite'
    | '/intranet'
    | '/partage/$jeton'
    | '/intranet/acquis'
    | '/intranet/admin'
    | '/intranet/budget'
    | '/intranet/coffre'
    | '/intranet/demande-formation'
    | '/intranet/formations'
    | '/intranet/positionnement'
    | '/intranet/profil'
    | '/intranet/'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/politique-confidentialite'
    | '/partage/$jeton'
    | '/intranet/acquis'
    | '/intranet/admin'
    | '/intranet/budget'
    | '/intranet/coffre'
    | '/intranet/demande-formation'
    | '/intranet/formations'
    | '/intranet/positionnement'
    | '/intranet/profil'
    | '/intranet'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/politique-confidentialite'
    | '/_authenticated/intranet'
    | '/partage/$jeton'
    | '/_authenticated/intranet/acquis'
    | '/_authenticated/intranet/admin'
    | '/_authenticated/intranet/budget'
    | '/_authenticated/intranet/coffre'
    | '/_authenticated/intranet/demande-formation'
    | '/_authenticated/intranet/formations'
    | '/_authenticated/intranet/positionnement'
    | '/_authenticated/intranet/profil'
    | '/_authenticated/intranet/'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PolitiqueConfidentialiteRoute: typeof PolitiqueConfidentialiteRoute
  PartageJetonRoute: typeof PartageJetonRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-confidentialite': {
      id: '/politique-confidentialite'
      path: '/politique-confidentialite'
      fullPath: '/politique-confidentialite'
      preLoaderRoute: typeof PolitiqueConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/intranet': {
      id: '/_authenticated/intranet'
      path: '/intranet'
      fullPath: '/intranet'
      preLoaderRoute: typeof AuthenticatedIntranetRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/partage/$jeton': {
      id: '/partage/$jeton'
      path: '/partage/$jeton'
      fullPath: '/partage/$jeton'
      preLoaderRoute: typeof PartageJetonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/intranet/': {
      id: '/_authenticated/intranet/'
      path: '/'
      fullPath: '/intranet/'
      preLoaderRoute: typeof AuthenticatedIntranetIndexRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/acquis': {
      id: '/_authenticated/intranet/acquis'
      path: '/acquis'
      fullPath: '/intranet/acquis'
      preLoaderRoute: typeof AuthenticatedIntranetAcquisRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/admin': {
      id: '/_authenticated/intranet/admin'
      path: '/admin'
      fullPath: '/intranet/admin'
      preLoaderRoute: typeof AuthenticatedIntranetAdminRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/budget': {
      id: '/_authenticated/intranet/budget'
      path: '/budget'
      fullPath: '/intranet/budget'
      preLoaderRoute: typeof AuthenticatedIntranetBudgetRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/coffre': {
      id: '/_authenticated/intranet/coffre'
      path: '/coffre'
      fullPath: '/intranet/coffre'
      preLoaderRoute: typeof AuthenticatedIntranetCoffreRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/demande-formation': {
      id: '/_authenticated/intranet/demande-formation'
      path: '/demande-formation'
      fullPath: '/intranet/demande-formation'
      preLoaderRoute: typeof AuthenticatedIntranetDemandeFormationRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/formations': {
      id: '/_authenticated/intranet/formations'
      path: '/formations'
      fullPath: '/intranet/formations'
      preLoaderRoute: typeof AuthenticatedIntranetFormationsRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/positionnement': {
      id: '/_authenticated/intranet/positionnement'
      path: '/positionnement'
      fullPath: '/intranet/positionnement'
      preLoaderRoute: typeof AuthenticatedIntranetPositionnementRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/_authenticated/intranet/profil': {
      id: '/_authenticated/intranet/profil'
      path: '/profil'
      fullPath: '/intranet/profil'
      preLoaderRoute: typeof AuthenticatedIntranetProfilRouteImport
      parentRoute: typeof AuthenticatedIntranetRouteRoute
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedIntranetRouteRouteChildren {
  AuthenticatedIntranetAcquisRoute: typeof AuthenticatedIntranetAcquisRoute
  AuthenticatedIntranetAdminRoute: typeof AuthenticatedIntranetAdminRoute
  AuthenticatedIntranetBudgetRoute: typeof AuthenticatedIntranetBudgetRoute
  AuthenticatedIntranetCoffreRoute: typeof AuthenticatedIntranetCoffreRoute
  AuthenticatedIntranetDemandeFormationRoute: typeof AuthenticatedIntranetDemandeFormationRoute
  AuthenticatedIntranetFormationsRoute: typeof AuthenticatedIntranetFormationsRoute
  AuthenticatedIntranetPositionnementRoute: typeof AuthenticatedIntranetPositionnementRoute
  AuthenticatedIntranetProfilRoute: typeof AuthenticatedIntranetProfilRoute
  AuthenticatedIntranetIndexRoute: typeof AuthenticatedIntranetIndexRoute
}

const AuthenticatedIntranetRouteRouteChildren: AuthenticatedIntranetRouteRouteChildren =
  {
    AuthenticatedIntranetAcquisRoute: AuthenticatedIntranetAcquisRoute,
    AuthenticatedIntranetAdminRoute: AuthenticatedIntranetAdminRoute,
    AuthenticatedIntranetBudgetRoute: AuthenticatedIntranetBudgetRoute,
    AuthenticatedIntranetCoffreRoute: AuthenticatedIntranetCoffreRoute,
    AuthenticatedIntranetDemandeFormationRoute:
      AuthenticatedIntranetDemandeFormationRoute,
    AuthenticatedIntranetFormationsRoute: AuthenticatedIntranetFormationsRoute,
    AuthenticatedIntranetPositionnementRoute:
      AuthenticatedIntranetPositionnementRoute,
    AuthenticatedIntranetProfilRoute: AuthenticatedIntranetProfilRoute,
    AuthenticatedIntranetIndexRoute: AuthenticatedIntranetIndexRoute,
  }

const AuthenticatedIntranetRouteRouteWithChildren =
  AuthenticatedIntranetRouteRoute._addFileChildren(
    AuthenticatedIntranetRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntranetRouteRoute: typeof AuthenticatedIntranetRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntranetRouteRoute: AuthenticatedIntranetRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PolitiqueConfidentialiteRoute: PolitiqueConfidentialiteRoute,
  PartageJetonRoute: PartageJetonRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
